[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
exchange = { workspace = true }
config = { workspace = true }
tokio = { workspace = true }
etcd = { workspace = true }
