{
 "title": "Indexer",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Websocket Messages Consumer",
   "type": "timeseries",
   "description": "The t",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(ws_consumer_messages{consumer=~\".*\"}[5m])",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "Dbwriter Messages Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(dbwriter_messages_written{}[5m])",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Dbwriter Messages Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(dbwriter_messages_dropped[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(distribution_messages_sent{}[5m])",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Distribution Messages Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(distribution_messages_dropped{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}