services:

  redis:
    image: "${REGISTRY_URL:-}redis:7-alpine"
    volumes:
      - ${PWD}/.tmp/redis:/data
    ports:
      - 6379:6379

  grafana:
    container_name: grafana
    image: "${REGISTRY_URL:-}grafana/grafana"
    ports:
      - "3000:3000"

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
  
  database:
    image: "${REGISTRY_URL:-}postgres:15-alpine"
    ports:
      - 6432:5432
    volumes:
      - ${PWD}/.tmp/pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "fsync=off", "-c", "full_page_writes=off"]
    env_file:
      - .dev.env
  
  
  jsonrpc-mock:
    image: "${REGISTRY_URL:-}mockserver/mockserver"
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/jsonrpc.json
    volumes:
      - ./mockserver:/config